/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';

clientsClaim();
cleanupOutdatedCaches();

const ASSETS = [
  // Assets generated by the build process
  ...self.__WB_MANIFEST,
  // Assets from the public directory
  ...process.env.REACT_APP_PUBLIC_FILES.split(',').map(file => ({
    revision: process.env.REACT_APP_PUBLIC_REV,
    url: `${process.env.PUBLIC_URL}/${file}`
  }))
];

precacheAndRoute(ASSETS);
console.log("Precache:", ASSETS);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

/*
Images from Rebrickable can be cached only as opaque responses. Not sure, keep it off for now.
https://developer.chrome.com/docs/workbox/caching-resources-during-runtime#opaque_responses

registerRoute(
  ({ request, url }) => {
    const matched = url.host === 'cdn.rebrickable.com' && request.destination === 'image';
    return matched;
  },
  new CacheFirst({
    cacheName: 'rebrickable',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);
*/
