/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';

clientsClaim();
cleanupOutdatedCaches();

const ASSETS = [
  // Assets generated by the build process
  ...self.__WB_MANIFEST,
  // Assets from the public directory
  ...process.env.REACT_APP_PUBLIC_FILES.split(',').map(file => ({
    revision: process.env.REACT_APP_PUBLIC_REV,
    url: `${process.env.PUBLIC_URL}/${file}`
  }))
];

precacheAndRoute(ASSETS);
console.log("Precache:", ASSETS);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
