name: Build JS

on:
  push:
    paths:
      - rbmerge.base.js
      - 'data/*.csv'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: build rbmerge.js
        run: ./build/build.sh

      - name: commit rbmerge.js
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: build/rbmerge.js
          commit_message: "bot: commit built rbmerge.js"
