name: Check DB

on:
  schedule:
    - cron: '10 8 * * *'  # daily at 8:10 UTC

  workflow_dispatch:

jobs:
  check-db:
    runs-on: ubuntu-latest
    steps:
      - name: Get Hash
        id: get-hash
        run: |
          curl -LO https://github.com/ojuuji/rb.db/releases/download/latest/rb.db.sha256
          echo "hash=$(cut -f1 -d' ' rb.db.sha256)" >> $GITHUB_OUTPUT
  
      - uses: actions/cache@v4
        id: cache
        with:
          path: rb.db.sha256
          key: steps.get-hash.outputs.hash
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
  
  deploy-site:
    needs: check-db
    if: needs.check-db.outputs.cache-hit != 'true'
    uses: ./.github/workflows/deploy-site.yml
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit
